### check if site is live
GET {{url}}/isalive

### create cpu load with no time limit
GET {{url}}/loads/cpu-no-time-limit

### create cpu load with no time limit
GET {{url}}/loads/cpu-with-time-limit?seconds=60
Accept: application/json


